import { BeltColor } from '../types';

export interface IBJJFBeltDefinition {
  id: BeltColor;
  name: string;
  category: 'kids' | 'adult' | 'master';
  ageRange: string;
  minAge: number;
  minTimeDescription: string;
  order: number;
  colorName: string;
  bicolorType: 'solid' | 'center_white' | 'center_black' | 'coral_black' | 'coral_white';
  baseColorClass: string;
  stripeColorClass?: string;
  borderColorClass: string;
  barBgClass: string;
  textColorClass: string;
  description: string;
  transitionRule?: string;
}

export const IBJJF_BELTS: Record<BeltColor, IBJJFBeltDefinition> = {
  // === FAIXA BRANCA (COMUM) ===
  white: {
    id: 'white',
    name: 'Branca',
    category: 'kids',
    ageRange: 'Qualquer idade (4 anos ou mais)',
    minAge: 4,
    minTimeDescription: 'Sem carência mínima oficial (critério do professor)',
    order: 1,
    colorName: 'Branca',
    bicolorType: 'solid',
    baseColorClass: 'bg-white',
    borderColorClass: 'border-slate-300 shadow-inner',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-slate-700',
    description: 'Faixa de início na arte suave. Foco em disciplina, sobrevivência, mobilidade básica e princípios de defesa pessoal.',
  },

  // === INFANTIL: GRUPO CINZA (4 a 15 anos) ===
  grey_white: {
    id: 'grey_white',
    name: 'Cinza e Branca',
    category: 'kids',
    ageRange: '4 a 15 anos',
    minAge: 4,
    minTimeDescription: 'Frequência regular (aprox. 3 a 6 meses)',
    order: 2,
    colorName: 'Cinza com listra branca',
    bicolorType: 'center_white',
    baseColorClass: 'bg-slate-400',
    stripeColorClass: 'bg-white',
    borderColorClass: 'border-slate-500',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-slate-200',
    description: 'Primeiro estágio do Grupo Cinza da IBJJF. Cinza com listra central horizontal branca.',
  },
  grey: {
    id: 'grey',
    name: 'Cinza',
    category: 'kids',
    ageRange: '4 a 15 anos',
    minAge: 4,
    minTimeDescription: 'Frequência regular (aprox. 6 a 12 meses)',
    order: 3,
    colorName: 'Cinza Lisa',
    bicolorType: 'solid',
    baseColorClass: 'bg-slate-400',
    borderColorClass: 'border-slate-500',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-slate-200',
    description: 'Segundo estágio do Grupo Cinza. Cinza sólida com tarja preta para graus.',
  },
  grey_black: {
    id: 'grey_black',
    name: 'Cinza e Preta',
    category: 'kids',
    ageRange: '4 a 15 anos',
    minAge: 4,
    minTimeDescription: 'Frequência regular com evolução técnica',
    order: 4,
    colorName: 'Cinza com listra preta',
    bicolorType: 'center_black',
    baseColorClass: 'bg-slate-400',
    stripeColorClass: 'bg-slate-950',
    borderColorClass: 'border-slate-500',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-slate-200',
    description: 'Terceiro e último estágio do Grupo Cinza antes da transição para o Grupo Amarelo.',
  },

  // === INFANTIL: GRUPO AMARELO (7 a 15 anos) ===
  yellow_white: {
    id: 'yellow_white',
    name: 'Amarela e Branca',
    category: 'kids',
    ageRange: '7 a 15 anos',
    minAge: 7,
    minTimeDescription: 'Idade mínima 7 anos completos',
    order: 5,
    colorName: 'Amarela com listra branca',
    bicolorType: 'center_white',
    baseColorClass: 'bg-amber-400',
    stripeColorClass: 'bg-white',
    borderColorClass: 'border-amber-500',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-amber-400',
    description: 'Início do Grupo Amarelo IBJJF. Alunos desenvolvem maior coordenação, quedas básicas e movimentações no solo.',
  },
  yellow: {
    id: 'yellow',
    name: 'Amarela',
    category: 'kids',
    ageRange: '7 a 15 anos',
    minAge: 7,
    minTimeDescription: 'Idade mínima 7 anos completos',
    order: 6,
    colorName: 'Amarela Lisa',
    bicolorType: 'solid',
    baseColorClass: 'bg-amber-400',
    borderColorClass: 'border-amber-500',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-amber-400',
    description: 'Estágio intermediário do Grupo Amarelo. Domínio de raspagens e controles posicionais.',
  },
  yellow_black: {
    id: 'yellow_black',
    name: 'Amarela e Preta',
    category: 'kids',
    ageRange: '7 a 15 anos',
    minAge: 7,
    minTimeDescription: 'Idade mínima 7 anos completos',
    order: 7,
    colorName: 'Amarela com listra preta',
    bicolorType: 'center_black',
    baseColorClass: 'bg-amber-400',
    stripeColorClass: 'bg-slate-950',
    borderColorClass: 'border-amber-500',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-amber-400',
    description: 'Último estágio do Grupo Amarelo. Preparação para o Grupo Laranja.',
  },

  // === INFANTIL: GRUPO LARANJA (10 a 15 anos) ===
  orange_white: {
    id: 'orange_white',
    name: 'Laranja e Branca',
    category: 'kids',
    ageRange: '10 a 15 anos',
    minAge: 10,
    minTimeDescription: 'Idade mínima 10 anos completos',
    order: 8,
    colorName: 'Laranja com listra branca',
    bicolorType: 'center_white',
    baseColorClass: 'bg-orange-500',
    stripeColorClass: 'bg-white',
    borderColorClass: 'border-orange-600',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-orange-400',
    description: 'Início do Grupo Laranja IBJJF. Atletas demonstram estratégia apurada e encadeamento técnico de golpes.',
  },
  orange: {
    id: 'orange',
    name: 'Laranja',
    category: 'kids',
    ageRange: '10 a 15 anos',
    minAge: 10,
    minTimeDescription: 'Idade mínima 10 anos completos',
    order: 9,
    colorName: 'Laranja Lisa',
    bicolorType: 'solid',
    baseColorClass: 'bg-orange-500',
    borderColorClass: 'border-orange-600',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-orange-400',
    description: 'Estágio intermediário do Grupo Laranja.',
  },
  orange_black: {
    id: 'orange_black',
    name: 'Laranja e Preta',
    category: 'kids',
    ageRange: '10 a 15 anos',
    minAge: 10,
    minTimeDescription: 'Idade mínima 10 anos completos',
    order: 10,
    colorName: 'Laranja com listra preta',
    bicolorType: 'center_black',
    baseColorClass: 'bg-orange-500',
    stripeColorClass: 'bg-slate-950',
    borderColorClass: 'border-orange-600',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-orange-400',
    description: 'Último estágio do Grupo Laranja antes de ingressar no Grupo Verde.',
  },

  // === INFANTIL: GRUPO VERDE (13 a 15 anos) ===
  green_white: {
    id: 'green_white',
    name: 'Verde e Branca',
    category: 'kids',
    ageRange: '13 a 15 anos',
    minAge: 13,
    minTimeDescription: 'Idade mínima 13 anos completos',
    order: 11,
    colorName: 'Verde com listra branca',
    bicolorType: 'center_white',
    baseColorClass: 'bg-emerald-600',
    stripeColorClass: 'bg-white',
    borderColorClass: 'border-emerald-700',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-emerald-400',
    description: 'Início do estágio avançado infantil. Atletas com alto rendimento técnico e bagagem competitiva.',
  },
  green: {
    id: 'green',
    name: 'Verde',
    category: 'kids',
    ageRange: '13 a 15 anos',
    minAge: 13,
    minTimeDescription: 'Idade mínima 13 anos completos',
    order: 12,
    colorName: 'Verde Lisa',
    bicolorType: 'solid',
    baseColorClass: 'bg-emerald-600',
    borderColorClass: 'border-emerald-700',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-emerald-400',
    description: 'Estágio intermediário do Grupo Verde.',
  },
  green_black: {
    id: 'green_black',
    name: 'Verde e Preta',
    category: 'kids',
    ageRange: '13 a 15 anos',
    minAge: 13,
    minTimeDescription: 'Idade mínima 13 anos completos',
    order: 13,
    colorName: 'Verde com listra preta',
    bicolorType: 'center_black',
    baseColorClass: 'bg-emerald-600',
    stripeColorClass: 'bg-slate-950',
    borderColorClass: 'border-emerald-700',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-emerald-400',
    description: 'Faixa máxima infantil da IBJJF. Ao completar 16 anos, o atleta pode ser graduado diretamente à Faixa Azul pelo professor.',
    transitionRule: 'Regra IBJJF aos 16 anos: Atleta Faixa Verde promovido diretamente para Faixa Azul ou Faixa Branca conforme avaliação do Mestre.',
  },

  // === ADULTO / JUVENIL (16+ ANOS) ===
  blue: {
    id: 'blue',
    name: 'Azul',
    category: 'adult',
    ageRange: 'A partir de 16 anos',
    minAge: 16,
    minTimeDescription: 'Carência mínima IBJJF: 2 anos',
    order: 14,
    colorName: 'Azul',
    bicolorType: 'solid',
    baseColorClass: 'bg-blue-600',
    borderColorClass: 'border-blue-700',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-blue-400',
    description: 'Primeira graduação adulta. Foco no aperfeiçoamento de repertório técnico, transições de guarda e finalizações.',
  },
  purple: {
    id: 'purple',
    name: 'Roxa',
    category: 'adult',
    ageRange: 'A partir de 17 anos',
    minAge: 17,
    minTimeDescription: 'Carência mínima IBJJF: 1 ano e 6 meses',
    order: 15,
    colorName: 'Roxa',
    bicolorType: 'solid',
    baseColorClass: 'bg-purple-700',
    borderColorClass: 'border-purple-800',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-purple-400',
    description: 'Fase de fluidez, estilo pessoal e desenvolvimento pedagógico (autorizado a auxiliar instrutores).',
  },
  brown: {
    id: 'brown',
    name: 'Marrom',
    category: 'adult',
    ageRange: 'A partir de 18 anos',
    minAge: 18,
    minTimeDescription: 'Carência mínima IBJJF: 1 ano',
    order: 16,
    colorName: 'Marrom',
    bicolorType: 'solid',
    baseColorClass: 'bg-amber-900',
    borderColorClass: 'border-amber-950',
    barBgClass: 'bg-slate-900',
    textColorClass: 'text-amber-600',
    description: 'Polimento final antes da faixa preta. Foco em precisão, controle sob pressão e ataques de chaves de perna/pé.',
  },
  black: {
    id: 'black',
    name: 'Preta',
    category: 'adult',
    ageRange: 'A partir de 19 anos',
    minAge: 19,
    minTimeDescription: 'Carência mínima de 31 anos na Faixa Preta para alcançar o 7º Grau',
    order: 17,
    colorName: 'Preta',
    bicolorType: 'solid',
    baseColorClass: 'bg-slate-950',
    borderColorClass: 'border-slate-800',
    barBgClass: 'bg-red-600',
    textColorClass: 'text-red-500',
    description: 'Graduação de Professor / Especialista. Tarja vermelha com ponteiras brancas nas extremidades.',
  },

  // === GRAUS SUPERIORES & MESTRES (CBJJ / IBJJF) ===
  red_black: {
    id: 'red_black',
    name: 'Vermelha e Preta (Coral)',
    category: 'master',
    ageRange: 'A partir de 50 anos',
    minAge: 50,
    minTimeDescription: '7 anos como Faixa Preta 6º Grau (7º Grau - Mestre)',
    order: 18,
    colorName: 'Coral (Vermelha e Preta)',
    bicolorType: 'coral_black',
    baseColorClass: 'bg-red-700',
    stripeColorClass: 'bg-slate-950',
    borderColorClass: 'border-red-900',
    barBgClass: 'bg-slate-950',
    textColorClass: 'text-red-400',
    description: 'Título de Mestre (7º Grau). Gomos alternados em vermelho e preto.',
  },
  red_white: {
    id: 'red_white',
    name: 'Vermelha e Branca (Coral)',
    category: 'master',
    ageRange: 'A partir de 57 anos',
    minAge: 57,
    minTimeDescription: '7 anos como Faixa Coral 7º Grau (8º Grau - Mestre)',
    order: 19,
    colorName: 'Coral (Vermelha e Branca)',
    bicolorType: 'coral_white',
    baseColorClass: 'bg-red-700',
    stripeColorClass: 'bg-white',
    borderColorClass: 'border-red-900',
    barBgClass: 'bg-slate-950',
    textColorClass: 'text-red-400',
    description: 'Título de Mestre (8º Grau). Gomos alternados em vermelho e branco.',
  },
  red: {
    id: 'red',
    name: 'Vermelha',
    category: 'master',
    ageRange: 'A partir de 67 anos',
    minAge: 67,
    minTimeDescription: '10 anos como Faixa Coral 8º Grau (9º Grau - Grande Mestre)',
    order: 20,
    colorName: 'Vermelha',
    bicolorType: 'solid',
    baseColorClass: 'bg-red-600',
    borderColorClass: 'border-red-800',
    barBgClass: 'bg-amber-400',
    textColorClass: 'text-red-500',
    description: 'Título de Grande Mestre (9º Grau). 10º Grau reservado historicamente apenas aos pioneiros irmãos Gracie.',
  },
};

/** Lista oficial de faixas infantis da IBJJF (13 faixas na ordem) */
export const IBJJF_KIDS_BELTS: IBJJFBeltDefinition[] = [
  IBJJF_BELTS.white,
  IBJJF_BELTS.grey_white,
  IBJJF_BELTS.grey,
  IBJJF_BELTS.grey_black,
  IBJJF_BELTS.yellow_white,
  IBJJF_BELTS.yellow,
  IBJJF_BELTS.yellow_black,
  IBJJF_BELTS.orange_white,
  IBJJF_BELTS.orange,
  IBJJF_BELTS.orange_black,
  IBJJF_BELTS.green_white,
  IBJJF_BELTS.green,
  IBJJF_BELTS.green_black,
];

/** Lista oficial de faixas adultas e mestres da IBJJF */
export const IBJJF_ADULT_BELTS: IBJJFBeltDefinition[] = [
  IBJJF_BELTS.white,
  IBJJF_BELTS.blue,
  IBJJF_BELTS.purple,
  IBJJF_BELTS.brown,
  IBJJF_BELTS.black,
  IBJJF_BELTS.red_black,
  IBJJF_BELTS.red_white,
  IBJJF_BELTS.red,
];

/** Lista completa de todas as faixas ordenadas */
export const ALL_IBJJF_BELTS: IBJJFBeltDefinition[] = Object.values(IBJJF_BELTS).sort(
  (a, b) => a.order - b.order
);

/** Helper para obter dados da faixa com fallback seguro */
export function getBeltInfo(belt: BeltColor | string): IBJJFBeltDefinition {
  return IBJJF_BELTS[belt as BeltColor] || IBJJF_BELTS.white;
}

/** Helper para determinar se a faixa é infantil */
export function isKidsBelt(belt: BeltColor | string): boolean {
  const b = getBeltInfo(belt);
  return b.category === 'kids' && belt !== 'white';
}
